DROP TABLE IF EXISTS UserTransaction;
DROP TABLE IF EXISTS UserItem;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Transaction;
DROP TABLE IF EXISTS MemberOf;
DROP TABLE IF EXISTS BillifyGroup;
DROP TABLE IF EXISTS User;